#ifndef CONSTANTS_H
#define CONSTANTS_H

#define FPS 60.0
#define FRAME_DELAY (1000.0 / FPS)

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define GRID_SIZE 3
#define GRID_WIDTH (WINDOW_WIDTH / GRID_SIZE)
#define GRID_HEIGHT (WINDOW_HEIGHT / GRID_SIZE)

#endif
